### ISSUE TITLE
BRICS Chain Token Smart Contract 

### ISSUE THREAD

**Issue by bricschain** [CallistoSecurity/Smart-contract-auditing#11]
# Audit request

Our smart contract is an ERC20 Contract.

# Source code

> Github: https://github.com/bricschain/bricschaintoken/blob/main/BRICSChainToken.sol
> BSC Scan: https://bscscan.com/token/0xaC3357e7Ed7D58bCd73DF237C5B6A303e18bbDFf

# Payment plan

... Write [x] at the checkbox of the payment plan that suits your needs ...

- [x] Standard (standard projects such as ICOs, ERC20, ERC223, ERC721, ERC721A tokens and NFTs fall in this category - 2 auditors. $600 + $1.2 per line of code / minimum $1200)
- [ ] Advanced (non-standard projects requiring more careful review - 3 auditors. $1200 + $1.5 per line / minimum $2400)
- [ ] Corporate (projects that require post-launch support - 3 auditors - Callisto Team will handle the bugbounty and provide a 1 month long period of technical support regarding the necessary security enhancement procedures and track/highlight any issues and potential threats - this plan allows to further apply for Callisto DAPP Insurance program)

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...
> First inform us about this critical mistakes, we will fix them and deploy and another contract with these flaws fixed.

... provide your conditions for publishing the report or leave only standard disclosure policy link ...

> [Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...

> Email: contact@bricschain.io
> Telegram: t.me/bricschain

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...

> Website: bricschain.io
> Twitter: twitter.com/bricschain
> Telegram: twitter.com/bricschain
> Github: github.com/bricschain

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...

> BSC

**Comment by yuriy77k** [comment]
The audit fee is 1000 USDT.
You may send USDT (ERC20 or BEP20) to: 0x6317c6944bd1cD3932d062cce39d7Fd602119529 (valid for Ethereum and Binance Smart Chain)

The estimated auditing time - is 7 days after payment.

**Comment by yuriy77k** [comment]
payment received
https://etherscan.io/tx/0x74dd7d4c248e3fcf58cf7423b39f8da04de9ec6ef77636a4b0102e5ba5128844

**Comment by yuriy77k** [comment]
# BRICS Token v2 Security Audit Report

# 1. Summary

[BRICS token](https://github.com/bricschain/bricschaintoken/tree/main) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/CallistoSecurity/Smart-contract-auditing)

# 2. In scope

Commit: c79279690b800be2a89abbb503620d7c0ca72b94

- [BRICSChainToken.sol](https://github.com/bricschain/bricschaintoken/blob/c79279690b800be2a89abbb503620d7c0ca72b94/BRICSChainToken.sol)

# 3. Findings

In total, **0 issues** were reported, including:

- 0 high severity issues.

- 0 medium severity issues.

- 0 low severity issues.

In total, **10 notes** were reported, including:

- 2 minor observations.

- 8 owner privileges.



## 3.1. Missing events access control.

### Severity: minor observation

### Description

Detect missing events for critical access control parameters.

### Code Snippet

- https://github.com/bricschain/bricschaintoken/blob/c79279690b800be2a89abbb503620d7c0ca72b94/BRICSChainToken.sol#L64-L68

### Recommendation

Emit an event for critical parameter changes.

## 3.2.  Owner Privileges.

### Severity: owner privileges

### Description
 
BlackList
 1. The `addBlackList` function restricts token transfers for the user.
 2. The `destroyBlackFunds` function resets the user's account to zero.

Pausable
 1. The `pause` function allows the owner to stop the `transfer` and `transferFrom` operations.
 
BRICSChainToken
1. The `deprecate` function allows the owner to change the address of the token at any time.
2. The `issue`, `mint`, `mintTo` functions allow the owner to issue an unlimited number of tokens.
3. The `redeem` function allows the owner to burn tokens, but no more than `balances[owner]`.
4. The `setParams` function allows the owner to change `basisPointsRate` and `maximumFee`, but not more than 20 and 50 respectively.
5. The `recoverTokens` function allows the owner to withdraw tokens after an upgrade.

### Recommendation
Since the owner has unlimited rights to do everything, ownership must be given to a contract with multiple signatures.


## 3.3. Follow good coding practice.

### Severity: minor observation

### Description

1. Unlocked Pragma.

Contracts should be deployed using the same compiler version/flags with which they have been tested. Locking the floating pragma, i.e. by not using ^ in pragma solidity ^0.4.17, ensures that contracts do not accidentally get deployed using a compiler version with unfixed bugs.

2. Missing docstrings.

The contracts in the code base lack documentation. This hinders reviewers’ understanding of the code’s intention, which is fundamental to correctly assessing not only security but also correctness. Additionally, docstrings improve readability and ease maintenance. They should explicitly explain the purpose or intention of the functions, the scenarios under which they can fail, the roles allowed to call them, the values returned, and the events emitted.

Consider thoroughly documenting all functions (and their parameters) that are part of the contracts’ public API. Functions implementing sensitive functionality, even if not public, should be documented as well. When writing docstrings, consider following the Ethereum Natural Specification Format (NatSpec).

3. Missing test suite.

The contract is missing a test suite to validate and verify the behavior of the contract functionalities. Add tests are recommended to ensure that the contract functions and behaves as expected.

4. Functions not used internally could be marked as external.

It's a good coding practice to mark a function external when it's not called within the contract but only from outside the contract.


# 4. Security practices

- [x] **Open-source contact**.
- [ ] **The contract should pass a bug bounty after the completion of the security audit.**
- [ ] **Public testing.**
- [ ] **Automated anomaly detection systems.** - NOT IMPLEMENTED. A simple anomaly detection algorithm is recommended to be implemented to detect behavior that is atypical compared to normal for this contract. For instance, the contract must halt deposits in case a large amount is withdrawn in a short period until the owner or the community of the contract approves further operations.
- [ ] **Multisig owner account.**
- [x] **Standard ERC20-related issues.** - IMPLEMENTED. It is known that every contract can potentially receive an unintended ERC20-token deposit without the ability to reject it even if the contract is not intended to receive or hold tokens. As a result, it is recommended to implement a function that will allow extracting any arbitrary number of tokens from the contract.
- [ ] **Crosschain address collisions.** ETH, ETC, CLO, etc. It is possible that a transaction can be sent to the address of your contract at another chain (as a result of a user mistake or some software fault). It is recommended that you deploy a "mock contract" that would allow you to withdraw any tokens from that address or prevent any funds deposits. Note that you can reject transactions of native tokens deposited, but you can not reject the deposits of ERC20 tokens. You can use this source code as a mock contract: [extractor contract source code](https://github.com/EthereumCommonwealth/GNT-emergency-extractor-contract/blob/master/extractor.sol). The address of a new contract deployed using `CREATE (0xf0)` opcode is assigned following this scheme `keccak256(rlp([sender, nonce]))`. Therefore you need to use the same address that was originally used at the main chain to deploy the mock contract at a transaction with the `nonce` that matches that on the original chain. _Example: If you have deployed your main contract with address 0x010101 at your 2021th transaction then you need to increase your nonce of 0x010101 address to 2020 at the chain where your mock contract will be deployed. Then you can deploy your mock contract with your 2021th transaction, and it will receive the same address as your mainnet contract._


# 5. Conclusion

The audited smart contract can be deployed. No security issues were found during the audit.

Users should pay attention to unlimited owner's privileges.

It is recommended to adhere to the security practices described in pt. 4 of this report to ensure the contract's operability and prevent any issues that are not directly related to the code of this smart contract.

# 6. Previous audit reports

- https://gist.github.com/yuriy77k/f6217b4dfb2ae433a3e2743a6ce050b6

**Comment by yuriy77k** [comment]
# BRICS Token v2 Security Audit Report

# 1. Summary

[BRICS token](https://github.com/bricschain/bricschaintoken/tree/main) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/CallistoSecurity/Smart-contract-auditing)

- Website: https://bricschain.io
- Twitter:  https://twitter.com/bricschain
- Telegram: https://t.me/bricschainchannel
- Github:  https://github.com/bricschain


# 2. In scope

Commit: f5442d2501e808c14484e48f14a97d3c3cd252a5

- [BRICSChainTokenV2.sol](https://github.com/bricschain/bricschaintoken/blob/f5442d2501e808c14484e48f14a97d3c3cd252a5/BRICSChainTokenV2.sol)

# 3. Findings

In total, **0 issues** were reported, including:

- 0 high severity issues.

- 0 medium severity issues.

- 0 low severity issues.

In total, **1 note** was reported, including:

- 1 owner privilege.



## 3.1. Owner Privilege.

### Severity: owner privileges

### Description

The `mint` function allow the owner to issue an unlimited number of tokens.

### Recommendation
Ownership must be given to a contract with multiple signatures to reduce risk of compromising owner's private key.



# 4. Security practices

- [x] **Open-source contact**.
- [ ] **The contract should pass a bug bounty after the completion of the security audit.**
- [ ] **Public testing.**
- [ ] **Automated anomaly detection systems.** - NOT IMPLEMENTED. A simple anomaly detection algorithm is recommended to be implemented to detect behavior that is atypical compared to normal for this contract. For instance, the contract must halt deposits in case a large amount is withdrawn in a short period until the owner or the community of the contract approves further operations.
- [ ] **Multisig owner account.**
- [x] **Standard ERC20-related issues.** - IMPLEMENTED. It is known that every contract can potentially receive an unintended ERC20-token deposit without the ability to reject it even if the contract is not intended to receive or hold tokens. As a result, it is recommended to implement a function that will allow extracting any arbitrary number of tokens from the contract.
- [ ] **Crosschain address collisions.** ETH, ETC, CLO, etc. It is possible that a transaction can be sent to the address of your contract at another chain (as a result of a user mistake or some software fault). It is recommended that you deploy a "mock contract" that would allow you to withdraw any tokens from that address or prevent any funds deposits. Note that you can reject transactions of native tokens deposited, but you can not reject the deposits of ERC20 tokens. You can use this source code as a mock contract: [extractor contract source code](https://github.com/EthereumCommonwealth/GNT-emergency-extractor-contract/blob/master/extractor.sol). The address of a new contract deployed using `CREATE (0xf0)` opcode is assigned following this scheme `keccak256(rlp([sender, nonce]))`. Therefore you need to use the same address that was originally used at the main chain to deploy the mock contract at a transaction with the `nonce` that matches that on the original chain. _Example: If you have deployed your main contract with address 0x010101 at your 2021th transaction then you need to increase your nonce of 0x010101 address to 2020 at the chain where your mock contract will be deployed. Then you can deploy your mock contract with your 2021th transaction, and it will receive the same address as your mainnet contract._


# 5. Conclusion

The audited smart contract can be deployed. No security issues were found during the audit.

Users should pay attention to owner's privilege to mint unlimited amount of tokens.

It is recommended to adhere to the security practices described in pt. 4 of this report to ensure the contract's operability and prevent any issues that are not directly related to the code of this smart contract.

# 6. Previous audit reports

- https://gist.github.com/yuriy77k/f6217b4dfb2ae433a3e2743a6ce050b6
