### ISSUE TITLE
Enduracoin

### ISSUE THREAD

**Issue by Enduracoin** [CallistoSecurity/Smart-contract-auditing#14]
# Audit request

... Briefly describe your smart-contract and its main purposes here ...

This is an update to our previously audited code which was audited by @yuriy77k and team.  
Significant updates were made to EnduracoinValue.sol and corresponding documentation changes.  Minor updates (.i.e. renamed some variables, etc.) occurred in other files.  Other than these, the code is for the most part the same.

# Source code

... Give a link to the source code of contracts ...

Same as previous.  https://github.com/Enduracoin/EnduracoinToken
Yuriy still has access.

# Payment plan

... Write [x] at the checkbox of the payment plan that suits your needs ...

_Depends on cost... Advanced or Corporate.  We would like to have assistance with a bugbounty and launch/deployment to chains.
In the previous audit, it was mentioned to deploy alt contracts on other chains to help prevent known, potential customer vulnerabilities.  Would like assistance with that._

- [ ] Standard (standard projects such as ICOs, ERC20, ERC223, ERC721, ERC721A tokens and NFTs fall in this category - 2 auditors. $600 + $1.2 per line of code / minimum $1200)
- [x] Advanced (non-standard projects requiring more careful review - 3 auditors. $1200 + $1.5 per line / minimum $2400)
- [x] Corporate (projects that require post-launch support - 3 auditors - Callisto Team will handle the bugbounty and provide a 1 month long period of technical support regarding the necessary security enhancement procedures and track/highlight any issues and potential threats - this plan allows to further apply for Callisto DAPP Insurance program)

# Disclosure policy

... Do you want us to publish the report as it is or to notify you privately in case of finding critical mistakes? ...
Please notify privately via email.  Thank you.

... provide your conditions for publishing the report or leave only standard disclosure policy link ...
Please notify privately. via email.  Thank you.

[Standard disclosure policy](https://github.com/EthereumCommonwealth/Auditing/blob/master/Standard_disclosure_policy.md).

# Contact information (optional)

... Provide information to contact you or the smart contract-developer in case high severity issues will be found ...
via email:  troy@enduracoin.org

... Provide information about the media resources of the project you want us to audit (website/ twitter account/ reddit/ telegram channel/ etc.) ...
Twitter / X:  #Enduracoin / @Enduracoin

# Platform

... In which network will your contract be deployed? (EOS/TRX/ETC/ETH/CLO/UBQ/something else ) ...
ETH - Ethereum

**Comment by Enduracoin** [comment]
Hello Callisto Team.  I'm checking in to see if you have everything you need for this request?  It should be fairly simple as most of it has passed audit previously.  Also, can you provide me an estimated timeframe?  
Thank you, Enduracoin team.

**Comment by chhajershrenik** [comment]
@Enduracoin Please wait for an update from @yuriy77k.

**Comment by yuriy77k** [comment]
@Enduracoin updated contracts have many changes. The audit fee is 1200 USDT (with a 50% discount).
You may send USDT (ERC20 or BEP20) to: 0x6317c6944bd1cD3932d062cce39d7Fd602119529 (valid for Ethereum and Binance Smart Chain)

The estimated auditing time - is 7 days after payment.

**Comment by Enduracoin** [comment]
@yuriy77k - Payment has been made and Etherscan shows completed.

**Comment by Enduracoin** [comment]
Hello @yuriy77k and team.  Just checking in on the status of our request.  Any chance it will be complete by end of the weekend?

**Comment by yuriy77k** [comment]
# EnduracoinToken v1.0.5.10152023 Security Audit Report

# 1. Summary

[EnduracoinToken v1.0.5.10152023](https://github.com/Enduracoin/EnduracoinToken/tree/main) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/CallistoSecurity/Smart-contract-auditing)

# 2. In scope

Commit [f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b](https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/)

- EnduracoinToken.sol
- EnduracoinValue.sol
- ManageApprovers.sol
- StringHelpers.sol
- ChangeRequests.sol

# 3. Findings

In total, **2 issues** were reported, including:

- 0 high severity issues.

- 1 medium severity issue.

- 1 low severity issue.

In total, **2 notes** were reported, including:

- 1 minor observation.

- 1 owner privilege.



## 3.1. Token functionality may be blocked for all users for the voting period

### Severity: medium

### Description

All major functions (`transfer`, `approve`, `transferFrom`, etc) of EnduracoinToken have the modifier `requiresMultiSig()`. 
This modifier applies to check vote results if `pendingChange.addrValueToChange == owner()`. It means that any approver who creates `newChangeRequest` with the parameter `addressToUse` equal to the owner address will block all tokens functionality until voting is finished.

### Code snipped

- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinToken.sol#L112
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/ChangeRequests.sol#L69
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinToken.sol#L72


## 3.2. Owner privileges

### Severity: owner privileges

### Description

50 Billion Enduracoin will be pre-minted to the owner's wallet. If tokens are burnt, the owner has the right to mint new tokens up to 50 Billion in total supply.


## 3.3. The transfer ownership does not remove the old owner's address from the approver list  

### Severity: low

### Description

In the function `execChangeRequest` when `ChangeType` is `transferOwnership` and if a new owner address has already been added to the approver list, the old address will not be removed from approvers. Only if a new owner isn't approved it will be added to the list and the old address will be removed.

### Code snipped

- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinToken.sol#L45-L47
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinToken.sol#L49-L50

### Recommendation

Rewrite this part: https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinToken.sol#L44-L53

like this:

```Solidity
            else if(pendingChangeType == uint8(ChangeType.transferOwnership)) { 
                if(validateApproverExists(owner())) 
                    _removeApprover(owner());
                if(!validateApproverExists(pendingChange.addrValueToChange)) 
                    _setApprover(pendingChange.addrValueToChange);
                transferOwnership(pendingChange.addrValueToChange); 
            }
```

## 3.4. Multiple minor observation

### Severity: minor observation

### Description

1. The modifier `requiresMultiSig` restricts `owner` from calling the function until voting is finished, but allows anybody else to call the function without restriction. Therefore, in the context of the contract `EnduracoinValue` it does not make any sense and can be removed or replaced by the modifier `onlyApprovers`.

- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinValue.sol#L166
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinValue.sol#L180
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinValue.sol#L189

2. The `getPendingChangeRequest()` is a view function, so does not require `onlyApprovers` modifier.
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/ChangeRequests.sol#L152

3. Owner can't create a change request for `transfer`, `approve`, `transferFrom`, `increaseAllowance` and must be the last approver in voting. If the owner votes earlier the change request can't be approved and all other approvers should vote against it to be able to create a new request. 
It creates an opportunity for a frontrunning attack by a malicious approver, where he can flip his vote just before the owner's vote (so the owner will not be the last approver).

4. In the `EnduracoinValue` contract the comment says: "`LASTDAY_OF_YEAR21` represents the last day of year 21 from the start date.", but value 8030 = 22 * 365. So it's the last day of year 22. Also, this number does not take into account years with 366 days.
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinValue.sol#L16-L17

5. In the `EnduracoinValue` contract the `currentDayInPeriod` should be in range from 0 to 364. Therefore condition `if(daysSinceStart > 365)` should be changed to `if(daysSinceStart >= 365)`. or can be removed at all.
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinValue.sol#L60

6. The modifier `requiresMultiSig()` has a check `(msg.sender == owner() && approverAddresses[msg.sender])`. The condition `approverAddresses[msg.sender]` will always be `True` if the `msg.sender` is the `owner()` address. Therefore the condition `approverAddresses[msg.sender]` can safely be removed.
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/ChangeRequests.sol#L69C12-L69C68

7. Change request types `setBaseValueAdjustment`, and `setDailyValueGainAdjustment` are unused in the contracts and can be removed.
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/ChangeRequests.sol#L42-L43

8. The `require` statement would never revert and is redundant since the contract would never be in a state where the function `transferOwnership()` would be directly accessible.
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinValue.sol#L168

9. Condition in the require statement would always be `False`, as the contract cannot access the function `removeApprover()` for the change type `ChangeType.renounceOwnership`.
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinValue.sol#L192C12-L192C68
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinToken.sol#L162C12-L162C68

9. Use custom errors to optimize gas usage and reduce deployment costs.

Starting from [Solidity v0.8.4](https://github.com/ethereum/solidity/releases/tag/v0.8.4), there is a convenient and gas-efficient way to explain to users why an operation failed through the use of custom errors. Until now, you could already use strings to give more information about failures (e.g., revert("Insufficient funds.");), but they are rather expensive, especially when it comes to deployment cost, and it is difficult to use dynamic information in them.

10. When a pending change is executed in `EnduracoinValue` contract the `executionResult` string is set to "Change Opposed!", but even if the change was successfully executed the event `ChangeRequestExecutedEvent` would be emitted with the opposed string instead of a success string. 
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinValue.sol#L147
- https://github.com/Enduracoin/EnduracoinToken/blob/f1a046ffb4a9fc42236b4b80b1de5b8bb84e034b/EnduracoinValue.sol#L154


# 4. Security practices

- [ ] **Open-source contact**.
- [ ] **The contract should pass a bug bounty after the completion of the security audit.**
- [ ] **Public testing.**
- [ ] **Automated anomaly detection systems.** - NOT IMPLEMENTED. A simple anomaly detection algorithm is recommended to be implemented to detect behavior that is atypical compared to normal for this contract. For instance, the contract must halt deposits if a large amount is being withdrawn quickly until the owner or the project community approves further operations.
- [ ] **Multisig owner account.**
- [ ] **Standard ERC20-related issues.** - NOT IMPLEMENTED. Every contract can potentially receive an unintended ERC20-token deposit without the ability to reject it, even if the contract is not intended to receive or hold tokens. As a result, it is recommended to implement a function that will allow extracting any arbitrary number of tokens from the contract.
- [ ] **Crosschain address collisions.** ETH, ETC, CLO, etc. It is possible that a transaction can be sent to the address of your contract at another chain (as a result of a user mistake or some software fault). It is recommended that you deploy a "mock contract" that would allow you to withdraw any tokens from that address or prevent any funds deposits. Note that you can reject transactions of native tokens deposited, but you can not reject the deposits of ERC20 tokens. You can use this source code as a mock contract: [extractor contract source code](https://github.com/EthereumCommonwealth/GNT-emergency-extractor-contract/blob/master/extractor.sol). The address of a new contract deployed using `CREATE (0xf0)` opcode is assigned following this scheme `keccak256(rlp([sender, nonce]))`. Therefore you need to use the same address that was originally used at the main chain to deploy the mock contract at a transaction with the `nonce` that matches that on the original chain. _Example: If you have deployed your main contract with address 0x010101 at your 2021st transaction, then you need to increase your nonce of 0x010101 address to 2020 at the chain where your mock contract will be deployed. Then you can deploy your mock contract with your 2021st transaction, and it will receive the same address as your mainnet contract._

# 5. Conclusion

The audited smart contract can't be deployed. Pointed issues should be fixed before deployment.

Users should pay attention to the contract owner's rights.

It is recommended to adhere to the security practices described in pt. 4 of this report to ensure the contract's operability and prevent any issues that are not directly related to the code of this smart contract.

# 6. Revealing audit reports

- https://gist.github.com/chhajershrenik/94305e9d12d1efa9a9362b8b8851fa60
- https://gist.github.com/SakshamGuruji3/2a3acb47307e0f5e1404a5e74afb5b63
- https://gist.github.com/greywolf12/1195510fb0aa329afa843fefa468777e

## 6.1. Previous audit reports

- v1: https://gist.github.com/yuriy77k/d374031c58202d6b1d57086dfecfc35c
- v2: https://gist.github.com/yuriy77k/af105a36bb8109bcafe742825efb4906
- v3: https://gist.github.com/yuriy77k/b84d523240684ca6c4e1d06fdad525c7
- v4: https://gist.github.com/yuriy77k/5890f3eea29767622baa41dc857620bd

**Comment by Enduracoin** [comment]
Thank you.  We will update and submit those changes for your review within a few days.

**Comment by Enduracoin** [comment]
Hello @yuriy77k and team.  We have uploaded the updates with remedies to section 3.1.  You may continue your audit review.  



We've one point of clarification to make regarding section 3.3. "_The transfer ownership does not remove the old owner's address from the approver list"_...  Lines 47-56 in token contract.

This section is working as designed.  There are 2 scenarios of which these lines of code address and are as follows: 

- [ ] 1. If the new owner is already an approver then all we do is switch ownership from one address to another.  No approvers are to be removed in this scenario.

- [ ] 2. If the new owner is not already an approver, then we remove the existing owner address from ownership and the approvers list, then we add the new owner and also add the new owner to the approvers list.

Only the latter scenario requires removing the existing owners address.

We hope this clarifies the expected functionality.

**Comment by yuriy77k** [comment]
@Enduracoin thank you for the explanation. We started to re-audit the contract.

**Comment by yuriy77k** [comment]
@Enduracoin the high severity issue was found. The report is sent to email.

**Comment by Enduracoin** [comment]
@yuriy77k - please provide steps to reproduce the halted transactions issue when a change request is in progress.  

The behavior from our testing does not reflect this.  For example, when we set a change request to transfer funds from the owner account to any other account, and the change has not yet been executed, we are still able to transfer tokens between all other accounts.  These transactions are not halted from our tests.  Obviously we are missing something.  Please advise.

Thank you

**Comment by Enduracoin** [comment]
@yuriy77k and team,  In response to your findings, modifications have been made to the value, token and change request contracts.  You may proceed with the audit review.

Thank you, @Enduracoin

**Comment by yuriy77k** [comment]
@Enduracoin the paid audit request includes the one free re-audit, which we already did. 
The next reaudit will cost 600 USDT.  You may send USDT (ERC20 or BEP20) to: 0x6317c6944bd1cD3932d062cce39d7Fd602119529 (valid for Ethereum and Binance Smart Chain)

**Comment by yuriy77k** [comment]
@Enduracoin I did qiuq

**Comment by Enduracoin** [comment]
@yuriy77k - I will update the remove approver today.  we will send the payment Tuesday or Wednesday.  We have to wait our transfer to clear on the exchange.  I’ll respond once payment is sent. 

Thank you.

**Comment by Enduracoin** [comment]
@yuriy77k - Updates have been made.  You may download / sync when ready.  Payment will be made as soon as we can.

**Comment by yuriy77k** [comment]
# EnduracoinToken v1.0.5 Security Audit Report

# 1. Summary

[EnduracoinToken](https://github.com/Enduracoin/EnduracoinToken/tree/main) smart contract security audit report performed by [Callisto Security Audit Department](https://github.com/CallistoSecurity/Smart-contract-auditing)

# 2. In scope

Commit [b9a32fc37a5a81748f68e42a3dcd6590cee08035](https://github.com/Enduracoin/EnduracoinToken/blob/b9a32fc37a5a81748f68e42a3dcd6590cee08035/)

- EnduracoinToken.sol
- EnduracoinValue.sol
- ManageApprovers.sol
- StringHelpers.sol
- ChangeRequests.sol

# 3. Findings

In total, **0 issues** were reported, including:

- 0 high severity issues.

- 0 medium severity issues.

- 0 low severity issues.

In total, **2 notes** were reported, including:

- 1 minor observation.

- 1 owner privilege.



## 3.1. Owner privileges

### Severity: owner privileges

### Description

50 Billion Enduracoin will be pre-minted to the owner's wallet.


## 3.2. A few minor observation

### Severity: minor observation

### Description

1. The `getPendingChangeRequest()` is a view function, so does not require `onlyApprovers` modifier.
- https://github.com/Enduracoin/EnduracoinToken/blob/b9a32fc37a5a81748f68e42a3dcd6590cee08035/ChangeRequests.sol#L152

2. Owner must be the final approver in voting for `transfer`, `approve`, `transferFrom`, `increaseAllowance`. If the owner votes earlier the change request can't be approved and all other approvers should vote against it to be able to create a new request. 
It creates an opportunity for a frontrunning attack by a malicious approver, where he can flip his vote just before the owner's vote (so the owner will not be the last approver).



# 4. Security practices

- [ ] **Open-source contact**.
- [ ] **The contract should pass a bug bounty after the completion of the security audit.**
- [ ] **Public testing.**
- [ ] **Automated anomaly detection systems.** - NOT IMPLEMENTED. A simple anomaly detection algorithm is recommended to be implemented to detect behavior that is atypical compared to normal for this contract. For instance, the contract must halt deposits if a large amount is being withdrawn quickly until the owner or the project community approves further operations.
- [ ] **Multisig owner account.**
- [ ] **Standard ERC20-related issues.** - NOT IMPLEMENTED. Every contract can potentially receive an unintended ERC20-token deposit without the ability to reject it, even if the contract is not intended to receive or hold tokens. As a result, it is recommended to implement a function that will allow extracting any arbitrary number of tokens from the contract.
- [ ] **Crosschain address collisions.** ETH, ETC, CLO, etc. It is possible that a transaction can be sent to the address of your contract at another chain (as a result of a user mistake or some software fault). It is recommended that you deploy a "mock contract" that would allow you to withdraw any tokens from that address or prevent any funds deposits. Note that you can reject transactions of native tokens deposited, but you can not reject the deposits of ERC20 tokens. You can use this source code as a mock contract: [extractor contract source code](https://github.com/EthereumCommonwealth/GNT-emergency-extractor-contract/blob/master/extractor.sol). The address of a new contract deployed using `CREATE (0xf0)` opcode is assigned following this scheme `keccak256(rlp([sender, nonce]))`. Therefore you need to use the same address that was originally used at the main chain to deploy the mock contract at a transaction with the `nonce` that matches that on the original chain. _Example: If you have deployed your main contract with address 0x010101 at your 2021st transaction, then you need to increase your nonce of 0x010101 address to 2020 at the chain where your mock contract will be deployed. Then you can deploy your mock contract with your 2021st transaction, and it will receive the same address as your mainnet contract._

# 5. Conclusion

The audited smart contract can be deployed. No security issues were found during the audit.

It is recommended to adhere to the security practices described in pt. 4 of this report to ensure the contract's operability and prevent any issues that are not directly related to the code of this smart contract.

## 6. Previous audit reports

- v1: https://gist.github.com/yuriy77k/d374031c58202d6b1d57086dfecfc35c
- v2: https://gist.github.com/yuriy77k/af105a36bb8109bcafe742825efb4906
- v3: https://gist.github.com/yuriy77k/b84d523240684ca6c4e1d06fdad525c7
- v4: https://gist.github.com/yuriy77k/5890f3eea29767622baa41dc857620bd
- v1.0.5.10152023: https://gist.github.com/yuriy77k/b58e28c2c667819dd8eab6ff6da0ad6c
- v1.0.5.11052023: https://gist.github.com/yuriy77k/0ee453e34c9b0cc4fd7129497d136cbf

**Comment by Enduracoin** [comment]
Hello @yuriy77k and team.  I checked my account and the exchange has not yet released my deposit so it’ll be a few more day before I can send the payment.  Thank you for your patience and apologies for the delay.  I will notify you as soon as I’ve sent it.

Sincerely, @Enduracoin

**Comment by yuriy77k** [comment]
Hello @Enduracoin 

No problem, we'll wait. 
We've completed the audit, so you can deploy the contract.

**Comment by Enduracoin** [comment]
Hello @yuriy77k

Payment has been submitted and shows completed.  
Since we purchased the Corporate plan, what is the process to engage your team if we need assistance within the next month?  I'm thinking specifically about the crosschain address collision recommendations.  

Thank you, @Enduracoin.

**Comment by yuriy77k** [comment]
@Enduracoin Sorry, but you did not buy the Corporate plan (the minimal cost is 10,000 USDT). You have paid for Advanced audit.

About the cross-chain address collision recommendations:

To deploy the contract on the same address but on different chains, you should use the same deployer address and nonce.
I recommend creating a new (unused) address for deployment and then deploying contracts in the same order on different chains.
For example, in the first transaction you should deploy the `EnduracoinToken` contract, and in the second transaction - deploy the `EnduracoinValue` contract.

Your contract doesn't have any chain-specific requirement, so can be deployed on most Ethereum-compatible blockchains.

**Comment by Enduracoin** [comment]
Hello @yuriy77k

What URL can I send interested person to that shows the completed audit results of the most recent submission that passed?  The links above are to the older audits.

**Comment by yuriy77k** [comment]
@Enduracoin 
This is links to audit report
